export const GET_MOVIE_LIST = 'GET_MOVIE_LIST';
export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_RECOMMENDED_MOVIES_SUCCESS = 'GET_RECOMMENDED_MOVIES_SUCCESS';
export const SORT_MOVIES_SUCCESS = 'SORT_MOVIES_SUCCESS';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';


