import React from "react";
import ErrorBoundary from "./ErrorBoundary";
import { mount, error, shallow } from "enzyme";
import { WARNING } from "../environment/const";
import renderer from "react-test-renderer";

function ProblemChild() {
  return null;
}

it("logs error message on error generated by child", () => {
  const wrapper = mount(
    <ErrorBoundary>
      <ProblemChild />
    </ErrorBoundary>
  );
  wrapper.find(ProblemChild).simulateError(error);
  console.log(wrapper.debug());
});

it("updates state correctly", () => {
  const result = ErrorBoundary.getDerivedStateFromError(error);
  expect(result).toEqual({
    hasError: true
  });
});

