import React from "react";
import ErrorBoundary from "./ErrorBoundary";
import { shallow, error } from "enzyme";
import { WARNING } from "../environment/const";

function ProblemChild() {
  return null;
}

it("logs error message on error generated by child", () => {
  const wrapper = shallow(
    <ErrorBoundary>
      <ProblemChild />
    </ErrorBoundary>
  );
  wrapper.find(ProblemChild).simulateError(error);
  console.log(wrapper.debug());
});

it("updates state correctly", () => {
  const result = ErrorBoundary.getDerivedStateFromError(error);
  expect(result).toEqual({
    hasError: true
  });
});

it("renders warning in case of error", () => {
  const wrapper = shallow(
    <ErrorBoundary>
      <ProblemChild />
    </ErrorBoundary>
  );
  wrapper.setState({ hasError: true });
  expect(wrapper.html()).toEqual("<h1>" + WARNING + "</h1>");
});
